spring:
  application:
    name: lastcall-eats
  profiles:
    active: dev

  datasource:
    driver-class-name: org.postgresql.Driver

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %5p [%X{traceId:-}] --- [%15.15t] %-40.40logger{39} : %m%n"
